// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Models
{
    public partial class PurchaseOrderDetail
    {
        public int? PurchaseOrderId { get; set; }
        public decimal? UnitPrice { get; set; }
        public short? OrderQty { get; set; }

        public decimal? TotalAmount => UnitPrice * OrderQty;
    }
}